"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MODULES = void 0;
var MODULES;
(function (MODULES) {
    MODULES["APP"] = "APP";
    MODULES["SESSION"] = "SESSION";
    MODULES["ROOT"] = "ROOT";
    MODULES["VERSION"] = "VERSION";
    MODULES["GROUP_PERMISSIONS"] = "GroupPermissions";
    MODULES["ORGANIZATIONS"] = "Organization";
    MODULES["USER"] = "USER";
    MODULES["PROFILE"] = "PROFILE";
    MODULES["PLUGINS"] = "Plugins";
    MODULES["GLOBAL_DATA_SOURCE"] = "DATA_SOURCE";
    MODULES["DATA_QUERY"] = "DataQueries";
    MODULES["THREAD"] = "Thread";
    MODULES["COMMENT"] = "Comment";
    MODULES["FOLDER"] = "Folder";
    MODULES["ORGANIZATION_VARIABLE"] = "OrgEnvironmentVariable";
    MODULES["ORGANIZATION_CONSTANT"] = "OrganizationConstant";
    MODULES["ORGANIZATION_USER"] = "OrganizationUser";
    MODULES["AUTH"] = "Auth";
    MODULES["METADATA"] = "Metadata";
    MODULES["FOLDER_APPS"] = "FolderApp";
    MODULES["CUSTOM_STYLES"] = "CustomStyles";
    MODULES["SMTP"] = "SMTP";
    MODULES["ONBOARDING"] = "Onboarding";
    MODULES["INSTANCE_SETTINGS"] = "instanceSettings";
    MODULES["LICENSING"] = "Licensing";
    MODULES["FILE"] = "file";
    MODULES["ORGANIZATION_THEMES"] = "organizationThemes";
    MODULES["APP_ENVIRONMENTS"] = "appEnvironments";
    MODULES["WHITE_LABELLING"] = "whiteLabelling";
    MODULES["LOGIN_CONFIGS"] = "loginConfigs";
    MODULES["CONFIGS"] = "configs";
    MODULES["WORKFLOWS"] = "workflows";
    MODULES["TOOLJET_DATABASE"] = "ToolJetDatabase";
    MODULES["IMPORT_EXPORT_RESOURCES"] = "ImportExportResources";
    MODULES["TEMPLATES"] = "Templates";
    MODULES["AI"] = "ai";
    MODULES["APP_PERMISSIONS"] = "AppPermissions";
    MODULES["AUDIT_LOGS"] = "auditLogs";
    MODULES["EXTERNAL_APIS"] = "externalApis";
    MODULES["ORGANIZATION_PAYMENTS"] = "organizationPayments";
    MODULES["MODULES"] = "Modules";
    MODULES["APP_GIT"] = "AppGit";
    MODULES["GIT_SYNC"] = "GitSync";
    MODULES["QUERY_FOLDERS"] = "QueryFolders";
})(MODULES || (exports.MODULES = MODULES = {}));
//# sourceMappingURL=modules.js.map